---
- hosts: all
  gather_facts: no
  tags: serviceedit
  vars_prompt:
    - name: confirm_serviceedit
      prompt: "Did you really want to make changes to this service? (true/false)"
      private: "False"
  pre_tasks:
    - name: Wait for connection if not available, timeout 600 seconds
      wait_for_connection:
        timeout: 600
        delay: 0
      when: wait_for_connection == true

  roles:
    - vivumlab_service-edit
